name: Run Python script

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # This line sets the action to run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.9.0 pandas==1.3.3

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@master

    - name: Run script
      run: |
        python tuni_cash.py
        sleep 300

    - name: Commit 
      run: |
        git config --global user.name 'AbderrahmenDJEBBI'
        git config --global user.email 'Abderrahmen.DJEBBI@esprit.tn'
        git add exchange_rate.csv
        git commit -m "Update exchange_rate.csv"

    - name: Push 
      run: |
        git remote add origin https://AbderrahmenDJEBBI:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/AbderrahmenDJEBBI/Web_Scraping.git
        git push origin HEAD:main
